#include "jalium_media.h"
#include "jalium_media_internal.h"
#include "and_yuv_simd.h"
#include "jalium_audio.h"
#include "jalium_video_surface.h"

#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>
#include <unistd.h>

static_assert(sizeof(jalium_video_decoder_gpu_descriptor_t) ==
              sizeof(JaliumVideoSurfaceDescriptor));
static_assert(sizeof(jalium_video_decoder_gpu_descriptor_t) == 216);
static_assert(offsetof(jalium_video_decoder_gpu_descriptor_t, planes) ==
              offsetof(JaliumVideoSurfaceDescriptor, planes));
static_assert(offsetof(jalium_video_decoder_gpu_descriptor_t, planes) == 56);
static_assert(offsetof(jalium_video_decoder_gpu_descriptor_t,
                       acquire_fence_fd) == 184);
static_assert(offsetof(jalium_video_decoder_gpu_descriptor_t,
                       lifetime_context) ==
              offsetof(JaliumVideoSurfaceDescriptor, lifetime_context));
static_assert(offsetof(jalium_video_decoder_gpu_descriptor_t,
                       lifetime_context) == 192);

namespace {

bool g_observed_renderable_rgb_dmabuf = false;

constexpr uint32_t DrmFourcc(char a, char b, char c, char d)
{
    return static_cast<uint32_t>(static_cast<uint8_t>(a)) |
           (static_cast<uint32_t>(static_cast<uint8_t>(b)) << 8) |
           (static_cast<uint32_t>(static_cast<uint8_t>(c)) << 16) |
           (static_cast<uint32_t>(static_cast<uint8_t>(d)) << 24);
}

bool IsRenderableRgbFourcc(uint32_t value)
{
    return value == DrmFourcc('A', 'R', '2', '4') ||
           value == DrmFourcc('X', 'R', '2', '4') ||
           value == DrmFourcc('A', 'B', '2', '4') ||
           value == DrmFourcc('X', 'B', '2', '4');
}

// 1x1 opaque red PNG.
constexpr uint8_t kPng[] = {
    0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,
    0x00,0x00,0x00,0x0d,0x49,0x48,0x44,0x52,
    0x00,0x00,0x00,0x01,0x00,0x00,0x00,0x01,
    0x08,0x04,0x00,0x00,0x00,0xb5,0x1c,0x0c,
    0x02,0x00,0x00,0x00,0x0b,0x49,0x44,0x41,
    0x54,0x78,0xda,0x63,0x64,0xf8,0x0f,0x00,
    0x01,0x05,0x01,0x01,0x27,0x18,0xe3,0x66,
    0x00,0x00,0x00,0x00,0x49,0x45,
    0x4e,0x44,0xae,0x42,0x60,0x82
};

// Structurally decodable 1x1 opaque-white PNG whose IDAT CRC is inconsistent.
// Windows WIC accepts this payload and it has appeared in application/test
// assets. Linux must preserve that compatibility instead of failing in the
// stricter GStreamer pngdec element before a frame is produced.
constexpr uint8_t kPngWithRecoverableIdatCrcMismatch[] = {
    0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,
    0x00,0x00,0x00,0x0d,0x49,0x48,0x44,0x52,
    0x00,0x00,0x00,0x01,0x00,0x00,0x00,0x01,
    0x08,0x04,0x00,0x00,0x00,0xb5,0x1c,0x0c,
    0x02,0x00,0x00,0x00,0x0b,0x49,0x44,0x41,
    0x54,0x78,0xda,0x63,0xfc,0xff,0x1f,0x00,
    0x03,0x03,0x02,0x00,0xee,0xfe,0xe2,0xed,
    0x00,0x00,0x00,0x00,0x49,0x45,
    0x4e,0x44,0xae,0x42,0x60,0x82
};

// Two fully composed 1x1 frames: red for 50 ms, then blue for 100 ms.
constexpr uint8_t kGif[] = {
    0x47,0x49,0x46,0x38,0x39,0x61,0x01,0x00,0x01,0x00,0x80,0x00,
    0x00,0xff,0x00,0x00,0x00,0x00,0xff,0x21,0xf9,0x04,0x00,0x05,
    0x00,0x00,0x00,0x2c,0x00,0x00,0x00,0x00,0x01,0x00,0x01,0x00,
    0x00,0x02,0x02,0x44,0x01,0x00,0x21,0xf9,0x04,0x00,0x0a,0x00,
    0x00,0x00,0x2c,0x00,0x00,0x00,0x00,0x01,0x00,0x01,0x00,0x00,
    0x02,0x02,0x4c,0x01,0x00,0x3b,
};

// Two 1x1 APNG frames: red for 100 ms, then blue for 250 ms. Each fdAT
// stream is a valid standalone PNG zlib stream, exercising the Linux APNG
// parser/compositor without an external fixture or command-line encoder.
constexpr uint8_t kApng[] = {
    0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,0x00,0x00,0x00,0x0d,
    0x49,0x48,0x44,0x52,0x00,0x00,0x00,0x01,0x00,0x00,0x00,0x01,
    0x08,0x06,0x00,0x00,0x00,0x1f,0x15,0xc4,0x89,0x00,0x00,0x00,
    0x08,0x61,0x63,0x54,0x4c,0x00,0x00,0x00,0x02,0x00,0x00,0x00,
    0x00,0xf3,0x8d,0x93,0x70,0x00,0x00,0x00,0x1a,0x66,0x63,0x54,
    0x4c,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x01,0x00,0x00,0x00,
    0x01,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x0a,0x00,
    0x64,0x00,0x00,0x6f,0xe6,0xe7,0xeb,0x00,0x00,0x00,0x0d,0x49,
    0x44,0x41,0x54,0x78,0x9c,0x63,0xf8,0xcf,0xc0,0xf0,0x1f,0x00,
    0x05,0x00,0x01,0xff,0x89,0x99,0x3d,0x1d,0x00,0x00,0x00,0x1a,
    0x66,0x63,0x54,0x4c,0x00,0x00,0x00,0x01,0x00,0x00,0x00,0x01,
    0x00,0x00,0x00,0x01,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
    0x00,0x19,0x00,0x64,0x00,0x00,0xd3,0xd5,0xe0,0x6d,0x00,0x00,
    0x00,0x11,0x66,0x64,0x41,0x54,0x00,0x00,0x00,0x02,0x78,0x9c,
    0x63,0x60,0x60,0xf8,0xff,0x1f,0x00,0x03,0x02,0x01,0xff,0xf5,
    0x7b,0xa5,0xd7,0x00,0x00,0x00,0x00,0x49,0x45,0x4e,0x44,0xae,
    0x42,0x60,0x82,
};

// Two lossless 2x2 animated WebP frames generated by libwebp_anim: opaque red
// followed by opaque blue. The first malformed zero duration is deliberately
// retained to prove the decoder applies the same 10 ms anti-spin floor as the
// GIF/APNG paths; the second frame lasts 300 ms.
constexpr uint8_t kAnimatedWebP[] = {
    0x52,0x49,0x46,0x46,0x84,0x00,0x00,0x00,0x57,0x45,0x42,0x50,
    0x56,0x50,0x38,0x58,0x0a,0x00,0x00,0x00,0x02,0x00,0x00,0x00,
    0x01,0x00,0x00,0x01,0x00,0x00,0x41,0x4e,0x49,0x4d,0x06,0x00,
    0x00,0x00,0xff,0xff,0xff,0xff,0x00,0x00,0x41,0x4e,0x4d,0x46,
    0x28,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x01,0x00,
    0x00,0x01,0x00,0x00,0x00,0x00,0x00,0x02,0x56,0x50,0x38,0x4c,
    0x0f,0x00,0x00,0x00,0x2f,0x01,0x40,0x00,0x00,0x07,0x10,0xed,
    0x8f,0xfe,0x07,0x22,0xa2,0xff,0x01,0x00,0x41,0x4e,0x4d,0x46,
    0x28,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x01,0x00,
    0x00,0x01,0x00,0x00,0x2c,0x01,0x00,0x00,0x56,0x50,0x38,0x4c,
    0x0f,0x00,0x00,0x00,0x2f,0x01,0x40,0x00,0x00,0x07,0x10,0x51,
    0xff,0xfe,0x07,0x22,0xa2,0xff,0x01,0x00,
};

// 2-frame, mono, 8 kHz, signed 16-bit PCM WAV. This decoder is built into the
// Jalium media library and must remain usable when GStreamer is unavailable.
constexpr uint8_t kWav[] = {
    'R','I','F','F', 40,0,0,0, 'W','A','V','E',
    'f','m','t',' ', 16,0,0,0, 1,0, 1,0,
    0x40,0x1f,0,0, 0x80,0x3e,0,0, 2,0, 16,0,
    'd','a','t','a', 4,0,0,0, 0,0, 0xff,0x7f
};

int Fail(const char* message, jalium_media_status_t status)
{
    std::fprintf(stderr, "%s: %d (%s)\n", message, static_cast<int>(status),
                 jalium_media_status_string(status));
    return 1;
}

void CountLifetimeRelease(uint64_t context)
{
    auto* count = reinterpret_cast<uint32_t*>(
        static_cast<uintptr_t>(context));
    if (count) ++*count;
}

bool LanguageMatches(
    const char* value, const char* iso_639_1, const char* iso_639_2)
{
    return value &&
        (std::strcmp(value, iso_639_1) == 0 ||
         std::strcmp(value, iso_639_2) == 0);
}

int TestVideoSource(const char* source, const char* label, bool expect_h264)
{
    jalium_video_decoder_t* decoder = nullptr;
    auto status = jalium_video_decoder_open_file(
        source, JALIUM_PF_BGRA8, &decoder);
    if (status != JALIUM_MEDIA_OK || !decoder) return Fail(label, status);

    jalium_video_info_t info{};
    status = jalium_video_decoder_get_info(decoder, &info);
    if (status != JALIUM_MEDIA_OK || info.width == 0 || info.height == 0 ||
        info.duration_seconds <= 0 ||
        (expect_h264 && info.active_codec != JALIUM_CODEC_H264)) {
        jalium_video_decoder_close(decoder);
        return Fail("video info/codec", status);
    }

    // A VA-capable machine may expose the first sample as dma-buf; a software
    // CI machine reports NOT_IMPLEMENTED. Both paths must remain usable and
    // the GPU descriptor must carry complete multi-plane/lifetime metadata.
    jalium_video_decoder_gpu_descriptor_t gpu{};
    int64_t gpu_pts = 0;
    int32_t gpu_keyframe = 0;
    status = jalium_video_decoder_read_gpu_frame_descriptor(
        decoder, &gpu, &gpu_pts, &gpu_keyframe);
    if (status == JALIUM_MEDIA_OK) {
        if (gpu.kind != JALIUM_VS_KIND_LINUX_DMABUF || gpu.plane_count != 1 ||
            !IsRenderableRgbFourcc(gpu.drm_fourcc) ||
            gpu.lifetime_context == 0 ||
            gpu.lifetime_retain_callback == 0 ||
            gpu.lifetime_release_callback == 0) {
            jalium_video_decoder_release_gpu_surface_descriptor(&gpu);
            jalium_video_decoder_close(decoder);
            return Fail("GPU descriptor metadata", JALIUM_MEDIA_E_DECODE_FAILED);
        }
        for (uint32_t i = 0; i < gpu.plane_count; ++i) {
            if (gpu.planes[i].fd < 0 || gpu.planes[i].stride_bytes == 0) {
                jalium_video_decoder_release_gpu_surface_descriptor(&gpu);
                jalium_video_decoder_close(decoder);
                return Fail("GPU descriptor plane", JALIUM_MEDIA_E_DECODE_FAILED);
            }
        }
        g_observed_renderable_rgb_dmabuf = true;
        if ((jalium_linux_media_capabilities() &
             JALIUM_LINUX_MEDIA_DMABUF_EXPORT) == 0) {
            jalium_video_decoder_release_gpu_surface_descriptor(&gpu);
            jalium_video_decoder_close(decoder);
            return Fail("DMABUF capability after real RGB export",
                        JALIUM_MEDIA_E_DECODE_FAILED);
        }
        jalium_video_decoder_release_gpu_surface_descriptor(&gpu);
        status = jalium_video_decoder_disable_gpu_output(decoder);
        if (status != JALIUM_MEDIA_OK) {
            jalium_video_decoder_close(decoder);
            return Fail("GPU to CPU fallback", status);
        }
    } else if (status != JALIUM_MEDIA_E_NOT_IMPLEMENTED) {
        jalium_video_decoder_close(decoder);
        return Fail("GPU descriptor probe", status);
    }

    jalium_video_frame_t frame{};
    status = jalium_video_decoder_read_frame(decoder, &frame);
    if (status != JALIUM_MEDIA_OK || !frame.pixels || frame.width == 0) {
        jalium_video_decoder_close(decoder);
        return Fail("video frame", status);
    }

    constexpr int64_t seek_target_us = 900000;
    status = jalium_video_decoder_seek_microseconds(decoder, seek_target_us);
    if (status != JALIUM_MEDIA_OK) {
        jalium_video_decoder_close(decoder);
        return Fail("video accurate seek", status);
    }
    status = jalium_video_decoder_read_frame(decoder, &frame);
    if (status != JALIUM_MEDIA_OK || frame.pts_microseconds < 750000) {
        jalium_video_decoder_close(decoder);
        return Fail("video frame after accurate seek", status);
    }
    jalium_video_decoder_close(decoder);
    return 0;
}

int TestTrackAndSubtitleSource(const char* source)
{
    jalium_media_track_info_t* tracks = nullptr;
    uint32_t track_count = 0;
    auto status = jalium_media_discover_tracks(source, &tracks, &track_count);
    if (status != JALIUM_MEDIA_OK) return Fail("track discovery", status);
    uint32_t audio_count = 0;
    uint32_t subtitle_count = 0;
    bool english_audio = false;
    bool japanese_audio = false;
    for (uint32_t i = 0; i < track_count; ++i) {
        if (tracks[i].kind == JALIUM_MEDIA_TRACK_AUDIO) {
            ++audio_count;
            // GstDiscoverer normalizes ISO-639 metadata to either the
            // two-letter or three-letter form depending on plugin version.
            english_audio |= LanguageMatches(tracks[i].language, "en", "eng");
            japanese_audio |= LanguageMatches(tracks[i].language, "ja", "jpn");
        } else if (tracks[i].kind == JALIUM_MEDIA_TRACK_SUBTITLE) {
            ++subtitle_count;
        }
    }
    jalium_media_tracks_free(tracks, track_count);
    if (audio_count != 2 || subtitle_count != 1 || !english_audio ||
        !japanese_audio) {
        return Fail("track metadata", JALIUM_MEDIA_E_DECODE_FAILED);
    }

    jalium_audio_decoder_t* audio = nullptr;
    status = jalium_linux_audio_decoder_open_track(source, 1, &audio);
    if (status != JALIUM_MEDIA_OK || !audio) return Fail("audio track 1", status);
    jalium_audio_info_t audio_info{};
    status = jalium_audio_decoder_get_info(audio, &audio_info);
    std::vector<float> samples(
        static_cast<size_t>(std::max(1u, audio_info.channels)) * 1024);
    uint32_t frames = 0;
    if (status == JALIUM_MEDIA_OK) {
        status = jalium_audio_decoder_read_frames(
            audio, samples.data(), 1024, &frames);
    }
    if (status == JALIUM_MEDIA_OK && frames > 0) {
        status = jalium_audio_decoder_seek_us(audio, 900000);
    }
    if (status == JALIUM_MEDIA_OK) {
        frames = 0;
        status = jalium_audio_decoder_read_frames(
            audio, samples.data(), 1024, &frames);
    }
    jalium_audio_decoder_close(audio);
    if (status != JALIUM_MEDIA_OK || frames == 0) {
        return Fail("selected audio track read", status);
    }

    jalium_subtitle_decoder_t* subtitle = nullptr;
    status = jalium_subtitle_decoder_open(source, 0, &subtitle);
    if (status != JALIUM_MEDIA_OK || !subtitle) {
        return Fail("subtitle open", status);
    }
    jalium_subtitle_cue_t cue{};
    status = jalium_subtitle_decoder_read_cue(subtitle, &cue);
    if (status != JALIUM_MEDIA_OK || !cue.utf8_text ||
        std::string(cue.utf8_text).find("Jalium subtitle smoke") ==
            std::string::npos ||
        cue.start_microseconds < 200000 || cue.duration_microseconds < 900000) {
        jalium_subtitle_decoder_close(subtitle);
        return Fail("subtitle cue", status);
    }
    status = jalium_subtitle_decoder_seek_us(subtitle, 1250000);
    if (status == JALIUM_MEDIA_OK) {
        status = jalium_subtitle_decoder_read_cue(subtitle, &cue);
    }
    if (status == JALIUM_MEDIA_OK &&
        (!cue.utf8_text ||
         std::string(cue.utf8_text).find("Second cue") == std::string::npos ||
         cue.start_microseconds < 1250000)) {
        status = JALIUM_MEDIA_E_DECODE_FAILED;
    }
    jalium_subtitle_decoder_close(subtitle);
    return status == JALIUM_MEDIA_OK ? 0 : Fail("subtitle seek/read", status);
}

} // namespace

int main(int argc, char** argv)
{
    const bool expect_no_gstreamer =
        argc > 1 && std::strcmp(argv[1], "--expect-no-gstreamer") == 0;
    const int media_argument = expect_no_gstreamer ? 2 : 1;

    auto status = jalium_media_initialize();
    if (status != JALIUM_MEDIA_OK) return Fail("initialize", status);

    uint32_t bounded_stride = 0;
    size_t bounded_size = 0;
    if (!jalium_media_compute_bgra_layout(
            4096, 4096, &bounded_stride, &bounded_size) ||
        bounded_stride != 4096u * 4u ||
        bounded_size != static_cast<size_t>(4096u) * 4096u * 4u ||
        jalium_media_compute_bgra_layout(
            20000, 20000, &bounded_stride, &bounded_size) ||
        bounded_stride != 0 || bounded_size != 0) {
        return Fail("bounded pixel buffer layout",
                    JALIUM_MEDIA_E_DECODE_FAILED);
    }
    uint8_t synthetic_plane[8]{};
    if (!jalium::media::android::IsYuvPlaneReadable(
            synthetic_plane, 8, 4, 1, 4, 2) ||
        jalium::media::android::IsYuvPlaneReadable(
            synthetic_plane, 7, 4, 1, 4, 2) ||
        jalium::media::android::IsYuvPlaneReadable(
            synthetic_plane, 8, -1, 1, 4, 2) ||
        jalium::media::android::IsYuvPlaneReadable(
            synthetic_plane, 8, 4, 2, 4, 2)) {
        return Fail("bounded Android YUV plane layout",
                    JALIUM_MEDIA_E_DECODE_FAILED);
    }
    const uint8_t oversized_input_sentinel = 0;
    jalium_image_t oversized_image{};
    status = jalium_image_decode_memory(
        &oversized_input_sentinel,
        JALIUM_MEDIA_MAX_ENCODED_IMAGE_BYTES + 1u,
        JALIUM_PF_BGRA8,
        &oversized_image);
    if (status != JALIUM_MEDIA_E_OUT_OF_MEMORY ||
        oversized_image.pixels != nullptr) {
        return Fail("bounded encoded image input", status);
    }

    // The descriptor release API is intentionally idempotent: managed and
    // renderer teardown paths can converge after an exception. Prove that the
    // producer lifetime is released exactly once and the descriptor is reset.
    uint32_t lifetime_release_count = 0;
    jalium_video_decoder_gpu_descriptor_t synthetic_gpu{};
    for (auto& plane : synthetic_gpu.planes) plane.fd = -1;
    synthetic_gpu.acquire_fence_fd = -1;
    synthetic_gpu.lifetime_context = static_cast<uint64_t>(
        reinterpret_cast<uintptr_t>(&lifetime_release_count));
    synthetic_gpu.lifetime_release_callback = static_cast<uint64_t>(
        reinterpret_cast<uintptr_t>(&CountLifetimeRelease));
    jalium_video_decoder_release_gpu_surface_descriptor(&synthetic_gpu);
    jalium_video_decoder_release_gpu_surface_descriptor(&synthetic_gpu);
    if (lifetime_release_count != 1 || synthetic_gpu.lifetime_context != 0 ||
        synthetic_gpu.lifetime_release_callback != 0) {
        return Fail("GPU descriptor lifetime release",
                    JALIUM_MEDIA_E_DECODE_FAILED);
    }

    jalium_image_t image{};
    status = jalium_image_decode_memory(
        kPng, sizeof(kPng), JALIUM_PF_BGRA8, &image);
    if (status != JALIUM_MEDIA_OK) return Fail("PNG decode", status);
    if (image.width != 1 || image.height != 1 || !image.pixels) {
        std::fprintf(stderr, "PNG decode returned an invalid image\n");
        return 1;
    }
    jalium_image_free(&image);

    status = jalium_image_decode_memory(
        kPngWithRecoverableIdatCrcMismatch,
        sizeof(kPngWithRecoverableIdatCrcMismatch),
        JALIUM_PF_RGBA8, &image);
    if (status != JALIUM_MEDIA_OK) {
        return Fail("recoverable PNG CRC decode", status);
    }
    if (image.width != 1 || image.height != 1 || !image.pixels ||
        image.pixels[0] != 0xff || image.pixels[1] != 0xff ||
        image.pixels[2] != 0xff || image.pixels[3] != 0xff) {
        std::fprintf(stderr, "recoverable PNG CRC decode returned invalid pixels\n");
        return 1;
    }
    jalium_image_free(&image);

    if (expect_no_gstreamer) {
        if (jalium_media_supported_video_codecs() != 0) {
            std::fprintf(stderr, "disabled GStreamer reported video codecs\n");
            return 1;
        }

        // A URI must bypass the local fopen/FileExists guard. With the loader
        // disabled it fails synchronously as an unavailable capability rather
        // than being misreported as a missing local file.
        jalium_video_decoder_t* uri_decoder = nullptr;
        status = jalium_video_decoder_open_file(
            "https://example.invalid/video.mp4", JALIUM_PF_BGRA8,
            &uri_decoder);
        if (status != JALIUM_MEDIA_E_NOT_IMPLEMENTED || uri_decoder) {
            return Fail("disabled GStreamer URI status", status);
        }
    }

    uint32_t animated_count = 0;
    status = jalium_image_read_frame_count(
        kGif, sizeof(kGif), &animated_count);
    if (status != JALIUM_MEDIA_OK || animated_count != 2) {
        return Fail("GIF frame count", status);
    }
    for (uint32_t frame_index = 0; frame_index < animated_count; ++frame_index) {
        uint32_t delay_ms = 0;
        status = jalium_image_decode_frame(
            kGif, sizeof(kGif), frame_index, JALIUM_PF_BGRA8,
            &image, &delay_ms);
        const uint32_t expected_delay = frame_index == 0 ? 50 : 100;
        if (status != JALIUM_MEDIA_OK || image.width != 1 ||
            image.height != 1 || !image.pixels || delay_ms != expected_delay) {
            return Fail("GIF frame decode", status);
        }
        jalium_image_free(&image);
    }

    animated_count = 0;
    status = jalium_image_read_frame_count(
        kApng, sizeof(kApng), &animated_count);
    if (expect_no_gstreamer) {
        if (status != JALIUM_MEDIA_E_NOT_IMPLEMENTED) {
            return Fail("disabled GStreamer APNG status", status);
        }
    } else {
#if JALIUM_TEST_HAS_GSTREAMER
        if (status != JALIUM_MEDIA_OK || animated_count != 2) {
            return Fail("APNG frame count", status);
        }
        uint32_t delay_ms = 0;
        status = jalium_image_decode_frame(
            kApng, sizeof(kApng), 1, JALIUM_PF_BGRA8,
            &image, &delay_ms);
        if (status != JALIUM_MEDIA_OK || delay_ms != 250 ||
            !image.pixels || image.pixels[0] != 0xff ||
            image.pixels[1] != 0x00 || image.pixels[2] != 0x00 ||
            image.pixels[3] != 0xff) {
            return Fail("APNG second frame", status);
        }
        jalium_image_free(&image);
#endif
    }

    animated_count = 0;
    status = jalium_image_read_frame_count(
        kAnimatedWebP, sizeof(kAnimatedWebP), &animated_count);
    if (status != JALIUM_MEDIA_OK || animated_count != 2) {
        return Fail("animated WebP frame count", status);
    }
    for (uint32_t frame_index = 0; frame_index < animated_count; ++frame_index) {
        uint32_t delay_ms = 0;
        status = jalium_image_decode_frame(
            kAnimatedWebP, sizeof(kAnimatedWebP), frame_index,
            JALIUM_PF_BGRA8, &image, &delay_ms);
        const uint32_t expected_delay = frame_index == 0 ? 10 : 300;
        const bool expected_red = frame_index == 0;
        if (status != JALIUM_MEDIA_OK || image.width != 2 ||
            image.height != 2 || !image.pixels ||
            delay_ms != expected_delay ||
            image.pixels[1] > 4 || image.pixels[3] != 0xff ||
            (expected_red
                ? image.pixels[0] > 4 || image.pixels[2] < 250
                : image.pixels[0] < 250 || image.pixels[2] > 4)) {
            std::fprintf(
                stderr,
                "animated WebP frame %u: %ux%u delay=%u pixel=%02x,%02x,%02x,%02x\n",
                frame_index, image.width, image.height, delay_ms,
                image.pixels ? image.pixels[0] : 0,
                image.pixels ? image.pixels[1] : 0,
                image.pixels ? image.pixels[2] : 0,
                image.pixels ? image.pixels[3] : 0);
            return Fail("animated WebP frame decode", status);
        }
        jalium_image_free(&image);
    }

    status = jalium_audio_initialize();
    if (status != JALIUM_MEDIA_OK) return Fail("audio initialize", status);
    jalium_audio_decoder_t* oversized_audio = nullptr;
    status = jalium_audio_decoder_open_memory(
        &oversized_input_sentinel,
        JALIUM_MEDIA_MAX_ENCODED_IMAGE_BYTES + 1u,
        JALIUM_ACODEC_WAV,
        &oversized_audio);
    if (status != JALIUM_MEDIA_E_OUT_OF_MEMORY || oversized_audio) {
        return Fail("bounded encoded audio input", status);
    }
    jalium_audio_decoder_t* wav = nullptr;
    status = jalium_audio_decoder_open_memory(
        kWav, sizeof(kWav), JALIUM_ACODEC_WAV, &wav);
    if (status != JALIUM_MEDIA_OK || !wav) return Fail("WAV open", status);
    jalium_audio_info_t wav_info{};
    status = jalium_audio_decoder_get_info(wav, &wav_info);
    if (status != JALIUM_MEDIA_OK || wav_info.sample_rate != 8000 ||
        wav_info.channels != 1 || wav_info.codec != JALIUM_ACODEC_WAV) {
        jalium_audio_decoder_close(wav);
        return Fail("WAV info", status);
    }
    float wav_frames[2]{};
    uint32_t wav_frames_read = 0;
    status = jalium_audio_decoder_read_frames(
        wav, wav_frames, 2, &wav_frames_read);
    if (status != JALIUM_MEDIA_OK || wav_frames_read == 0) {
        jalium_audio_decoder_close(wav);
        return Fail("WAV read", status);
    }
    jalium_audio_decoder_close(wav);

    char wav_path[] = "/tmp/jalium-audio-stream-XXXXXX";
    const int wav_fd = mkstemp(wav_path);
    if (wav_fd < 0 ||
        write(wav_fd, kWav, sizeof(kWav)) !=
            static_cast<ssize_t>(sizeof(kWav))) {
        if (wav_fd >= 0) close(wav_fd);
        if (wav_fd >= 0) unlink(wav_path);
        return Fail("WAV streaming fixture", JALIUM_MEDIA_E_IO);
    }
    close(wav_fd);
    jalium_audio_decoder_t* wav_file = nullptr;
    status = jalium_audio_decoder_open_file(
        wav_path, JALIUM_ACODEC_WAV, &wav_file);
    unlink(wav_path);
    if (status != JALIUM_MEDIA_OK || !wav_file) {
        return Fail("WAV streaming file open", status);
    }
    wav_frames_read = 0;
    status = jalium_audio_decoder_read_frames(
        wav_file, wav_frames, 2, &wav_frames_read);
    jalium_audio_decoder_close(wav_file);
    if (status != JALIUM_MEDIA_OK || wav_frames_read == 0) {
        return Fail("WAV streaming file read", status);
    }

    jalium_audio_shutdown();

    jalium_video_decoder_t* decoder = nullptr;
    status = jalium_video_decoder_open_file(
        "/definitely/not/a/jalium-video.mp4", JALIUM_PF_BGRA8, &decoder);
    if (status != JALIUM_MEDIA_E_IO || decoder != nullptr) {
        return Fail("missing video", status);
    }

    if (argc > media_argument &&
        TestVideoSource(argv[media_argument], "video open", true) != 0) {
        return 1;
    }

    if (argc > media_argument + 1) {
        status = jalium_audio_initialize();
        if (status != JALIUM_MEDIA_OK) return Fail("audio initialize", status);
        jalium_audio_decoder_t* audio = nullptr;
        status = jalium_audio_decoder_open_file(
            argv[media_argument + 1], JALIUM_ACODEC_AAC, &audio);
        if (status != JALIUM_MEDIA_OK || !audio) return Fail("AAC open", status);
        jalium_audio_info_t info{};
        status = jalium_audio_decoder_get_info(audio, &info);
        if (status != JALIUM_MEDIA_OK || info.sample_rate == 0 ||
            info.channels == 0 || info.codec != JALIUM_ACODEC_AAC) {
            jalium_audio_decoder_close(audio);
            return Fail("AAC info", status);
        }
        std::vector<float> pcm(static_cast<size_t>(info.channels) * 1024);
        uint32_t frames = 0;
        status = jalium_audio_decoder_read_frames(
            audio, pcm.data(), 1024, &frames);
        if (status != JALIUM_MEDIA_OK || frames == 0) {
            jalium_audio_decoder_close(audio);
            return Fail("AAC read", status);
        }
        status = jalium_audio_decoder_seek_us(audio, 0);
        if (status != JALIUM_MEDIA_OK) {
            jalium_audio_decoder_close(audio);
            return Fail("AAC seek", status);
        }
        jalium_audio_decoder_close(audio);
        jalium_audio_shutdown();
    }

    if (argc > media_argument + 2) {
        status = jalium_audio_initialize();
        if (status != JALIUM_MEDIA_OK) return Fail("audio initialize", status);
        const int result = TestTrackAndSubtitleSource(
            argv[media_argument + 2]);
        jalium_audio_shutdown();
        if (result != 0) return result;
    }

    if (argc > media_argument + 3) {
        if (TestVideoSource(argv[media_argument + 3], "HTTP video open", true) !=
            0) {
            return 1;
        }
        status = jalium_audio_initialize();
        if (status != JALIUM_MEDIA_OK) return Fail("audio initialize", status);
        const int result = TestTrackAndSubtitleSource(
            argv[media_argument + 3]);
        jalium_audio_shutdown();
        if (result != 0) return result;
    }

    const bool advertised_rgb_dmabuf =
        (jalium_linux_media_capabilities() &
         JALIUM_LINUX_MEDIA_DMABUF_EXPORT) != 0;
    if (advertised_rgb_dmabuf != g_observed_renderable_rgb_dmabuf) {
        return Fail("DMABUF capability requires an observed renderable export",
                    JALIUM_MEDIA_E_DECODE_FAILED);
    }

    jalium_camera_device_t* devices = nullptr;
    uint32_t count = 0;
    status = jalium_camera_enumerate(&devices, &count);
    if (status != JALIUM_MEDIA_OK &&
        status != JALIUM_MEDIA_E_NOT_IMPLEMENTED) {
        return Fail("camera enumerate", status);
    }
    jalium_camera_devices_free(devices, count);

    jalium_camera_source_t* missing_camera = nullptr;
    status = jalium_camera_open(
        "__jalium_missing_camera__", 640, 480, 30.0,
        JALIUM_PF_BGRA8, &missing_camera);
#if JALIUM_TEST_HAS_GSTREAMER
    const auto expected_missing_camera_status = expect_no_gstreamer
        ? JALIUM_MEDIA_E_NOT_IMPLEMENTED : JALIUM_MEDIA_E_NO_DEVICE;
#else
    const auto expected_missing_camera_status = JALIUM_MEDIA_E_NO_DEVICE;
#endif
    if (status != expected_missing_camera_status || missing_camera) {
        if (missing_camera) jalium_camera_close(missing_camera);
        return Fail("missing camera open", status);
    }

    jalium_microphone_device_t* microphones = nullptr;
    count = 0;
    status = jalium_microphone_enumerate(&microphones, &count);
    if (status != JALIUM_MEDIA_OK &&
        status != JALIUM_MEDIA_E_NOT_IMPLEMENTED) {
        return Fail("microphone enumerate", status);
    }
    jalium_microphone_devices_free(microphones, count);

    jalium_microphone_source_t* missing_microphone = nullptr;
    status = jalium_microphone_open(
        "__jalium_missing_microphone__", 48000, 1, &missing_microphone);
#if JALIUM_TEST_HAS_GSTREAMER
    const auto expected_missing_microphone_status = expect_no_gstreamer
        ? JALIUM_MEDIA_E_NOT_IMPLEMENTED : JALIUM_MEDIA_E_NO_DEVICE;
#else
    const auto expected_missing_microphone_status =
        JALIUM_MEDIA_E_NOT_IMPLEMENTED;
#endif
    if (status != expected_missing_microphone_status || missing_microphone) {
        if (missing_microphone) jalium_microphone_close(missing_microphone);
        return Fail("missing microphone open", status);
    }

    jalium_media_shutdown();

    // A fresh lifecycle must be able to reuse (or deliberately decline) the
    // optional capability. GStreamer itself remains process-lifetime once
    // loaded; gst_deinit/dlclose is not safe while plugin modules retain refs.
    status = jalium_media_initialize();
    if (status != JALIUM_MEDIA_OK) return Fail("reinitialize", status);
    jalium_media_shutdown();
    return 0;
}
