<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Jalium.UI.NuGetTest.Desktop</RootNamespace>
    <IsPackable>false</IsPackable>
    <JaliumPackageVersion Condition="'$(JaliumPackageVersion)' == ''">$(Version)</JaliumPackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jalium.UI.Desktop" Version="$(JaliumPackageVersion)" />
  </ItemGroup>

</Project>
