using System.Runtime.CompilerServices;
using Jalium.UI.Markup;

[assembly: InternalsVisibleTo("Jalium.UI.Input")]
[assembly: InternalsVisibleTo("Jalium.UI.Controls")]
[assembly: InternalsVisibleTo("Jalium.UI.Interop")]
[assembly: InternalsVisibleTo("Jalium.UI.Xaml")]
[assembly: InternalsVisibleTo("Jalium.UI.Media")]
[assembly: InternalsVisibleTo("Jalium.UI.DeviceLostHarness")]
[assembly: InternalsVisibleTo("Jalium.UI.Tests")]
[assembly: InternalsVisibleTo("ReactiveUI.Wpf")]
[assembly: InternalsVisibleTo("Jalium.UI.Desktop")]
[assembly: InternalsVisibleTo("Jalium.UI.Android")]
[assembly: InternalsVisibleTo("Jalium.UI.LinuxPortalSmoke")]

[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Automation")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Automation.Peers")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Collections")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Data")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Documents")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Input")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Interactivity")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Markup")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Media")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Media.Animation")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Media.Effects")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Media.Imaging")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Media.Media3D")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Media.TextFormatting")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Threading")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Controls")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Annotations")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Annotations.Storage")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Controls.Automation")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Controls.Charts")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Controls.DevTools")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Controls.Helpers")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Controls.Ink")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Ink")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Input.StylusPlugIns")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Controls.Navigation")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Controls.Primitives")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Controls.Ribbon")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Shapes")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Controls.Shell")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Shell")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Controls.TextEffects")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Controls.TextEffects.Effects")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Controls.Virtualization")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Documents.DocumentStructures")]
[assembly: XmlnsDefinition(JalxamlNamespaces.Presentation, "Jalium.UI.Hosting")]

[assembly: XmlnsCompatibleWith(JalxamlNamespaces.LegacyJaliumUi, JalxamlNamespaces.Presentation)]
[assembly: XmlnsCompatibleWith(JalxamlNamespaces.LegacyJaliumDev, JalxamlNamespaces.Presentation)]
[assembly: XmlnsCompatibleWith(JalxamlNamespaces.WpfPresentation, JalxamlNamespaces.Presentation)]

[assembly: XmlnsPrefix(JalxamlNamespaces.Presentation, "ui")]
[assembly: XmlnsPrefix(JalxamlNamespaces.XamlMarkup, "x")]
